spring:
  config:
    import: optional:configserver:http://config-service:8888
    retry:
      initial-interval: 3000
      max-interval: 10000
      max-attempts: 20
      multiplier: 1.3
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 20
        multiplier: 1.3
    discovery:
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 20
        multiplier: 1.3
  application:
    name: recipe-service
