# Find-Chop Config Server Dockerfile
FROM gradle:8.12.0-jdk23-alpine AS build

# Update Alpine Linux packages
RUN apk update && \
    apk upgrade && \
    rm -rf /var/cache/apk/*

COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle clean
RUN gradle build --no-daemon
#-------------------------------------------------
FROM openjdk:23-jdk-slim

# Update Debian-based packages and clean up
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8888

RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/config-server.jar

ENTRYPOINT ["java", "-jar", "/app/config-server.jar"]
#ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/config-server.jar"]