#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  application:
#    name: ingredient-service

spring:
  jackson:
    default-property-inclusion: non_null
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ingredient-service
springdoc:
  swagger-ui:
    path: /swagger