# Find-Chop Ingredient API Dockerfile
FROM gradle:8.12.0-jdk23-alpine AS build

# Update Alpine Linux packages
RUN apk update && \
    apk upgrade && \
    rm -rf /var/cache/apk/*

COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle clean
RUN gradle build --no-daemon
#-------------------------------------------------
FROM openjdk:23-jdk-slim

# Update Debian-based packages and clean up
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8098

RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/ingredient-api.jar

ENTRYPOINT ["java", "-jar", "/app/config-server.jar"]